'use strict';

const en = {
	email: 'Email',
	password: 'Password',
	login: 'Login',
	user: 'User',
	home: "Home",
	report: "Report",
	menu: "Menu",
    setting: "Setting",
	message: "Message",
	logOut: "Log Out",
	cancel: "Cancel",
	back: "Back",
	ok: "Ok",
	today: "Today",
	sales: "Sales",
	salesReport: "Sales report",
	warehouse: "Warehouse",
	warehouseReport: "Warehouse report",
	revenueToday: "Revenue today",
	invoice: "Invoice",
	quantity: "Quantity",
	grossProfit: "Gross profit",
	revenueByDate: "Revenue chart by day",
	logoutAccount: "Logout account",
	callorsms: 'You can text or call to customers',
	call: "Call",
	sms: "SMS",
	filter: 'Filter',
	all: 'All',
	branch: 'Branch',
	sokho: "Warehouse book",
    items: "Items",
    product: "Product",
    signUp: "Sign Up",
    forgotPassword: "Forgot Password",
    passWord: "Password",
    confirmPassword: "Confirm Password",
    needHelp: "Need Help?",
    checkingEmail: "Please enter a valid email address",
    checkingPassword: "Please enter at least 8 characters",
    checkingConfirmPass: "Please enter the same password",
    success: "Success",
    getCode: "Get code",
    changePassword: "Change password",
    typeEmail: "Type email",
    typeCode: "Type code",
    typeNewPassword: "Type new password",
    changePassSuccess: "Change password successfully",
    device: "Device",
    script: "Script",
    homeMessage: "You are not connected to the device. Add them for control and timer anywhere.",
    start: "Start",
}

export default en;