'use strict';

const vn = {
	email: 'Email',
	password: 'Mật khẩu',
	login: 'Đăng nhập',
	user: 'Người dùng',
	home: "Nhà",
	report: "Báo cáo",
	menu: "Menu",
    setting: "Cài đặt",
	message: "Thông báo",
	logOut: "Đăng xuất",
	cancel: "Hủy",
	back: "Quay lại",
	ok: "Đồng ý",
	today: "Hôm nay",
	sales: "Bán hàng",
	salesReport: "Báo cáo bán hàng",
	warehouse: "Kho",
	warehouseReport: "Báo cáo tồn kho",
	revenueToday: "Doanh thu hôm nay",
	invoice: "Hóa đơn",
	quantity: "Số lượng",
	grossProfit: "Lợi nhuận gộp",
	revenueByDate: "Biểu đồ doanh thu theo ngày",
	logoutAccount: "Đăng xuất tài khoản",
	callorsms: 'Bạn có thể nhắn tin hoặc gọi điện cho khách hàng',
	call: "Gọi",
	sms: "Tin nhắn",
	filter: 'Bộ lọc',
	all: 'Tất cả',
	branch: 'Chi nhánh',
	sokho: "Sổ kho",
    items: "Mặt hàng",
    product: "Sản phẩm",
    signUp: "Đăng ký",
    forgotPassword: "Quên mật khẩu",
    passWord: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    needHelp: "Bạn cần hỗ trợ?",
    checkingEmail: "Sai định dạng email",
    checkingPassword: "Mật khẩu phải có tối thiểu 8 ký tự",
    checkingConfirmPass: "Mật khẩu không khớp",
    success: "Thành công",
    getCode: "Nhận mã",
    changePassword: "Đổi mật khẩu",
    typeEmail: "Nhập email",
    typeCode: "Nhập mã",
    typeNewPassword: "Nhập mật khẩu mới",
    changePassSuccess: "Đổi mật khẩu thành công",
    device: "Thiết bị",
    script: "Kịch bản",
    homeMessage: "Bạn chưa kết nối đến thiết bị nào. Hãy thêm để điều khiển và hẹn giờ ở bất kỳ đâu.",
    start: "Bắt đầu",
}

export default vn;